# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomerApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
pod 'Firebase/Firestore'
  # Pods for CustomerApp

  target 'CustomerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomerAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
