# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SilverlineSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
pod 'Firebase/Firestore'
  # Pods for SilverlineSwift

  target 'SilverlineSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SilverlineSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
